//@ui5-bundle com/capm/userinspect/Component-preload.js
sap.ui.require.preload({
	"com/capm/userinspect/Component.js":function(){
sap.ui.define(["sap/fe/core/AppComponent"],function(e){"use strict";return e.extend("com.capm.userinspect.Component",{metadata:{manifest:"json"}})});
},
	"com/capm/userinspect/i18n/i18n.properties":'appTitle=User Inspect\nappDescription=View current user identity and IAS attributes\n',
	"com/capm/userinspect/i18n/i18n_en.properties":'appTitle=User Inspect\nappDescription=View current user identity and IAS attributes\n',
	"com/capm/userinspect/manifest.json":'{"_version":"1.65.0","sap.app":{"id":"com.capm.userinspect","type":"application","i18n":"i18n/i18n.properties","title":"{{appTitle}}","description":"{{appDescription}}","applicationVersion":{"version":"1.0.0"},"dataSources":{"mainService":{"uri":"/odata/v4/user-inspect/","type":"OData","settings":{"odataVersion":"4.0"}}},"crossNavigation":{"inbounds":{"UserInspect-display":{"semanticObject":"UserInspect","action":"display","title":"{{appTitle}}","signature":{"parameters":{},"additionalParameters":"allowed"}}}}},"sap.ui":{"technology":"UI5","fullWidth":true,"deviceTypes":{"desktop":true,"tablet":true,"phone":false}},"sap.fiori":{"registrationIds":[],"archeType":"analytical"},"sap.ui5":{"flexEnabled":false,"dependencies":{"minUI5Version":"1.120.0","libs":{"sap.ui.core":{},"sap.fe.templates":{},"sap.m":{},"sap.f":{}}},"contentDensities":{"compact":true,"cozy":true},"rootView":{"viewName":"sap.fe.core.rootView.NavContainer","type":"XML","async":true,"id":"appRootView"},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"com.capm.userinspect.i18n.i18n"}},"":{"dataSource":"mainService","preload":true,"settings":{"synchronizationMode":"None","operationMode":"Server","autoExpandSelect":true,"earlyRequests":true,"groupId":"$direct"}}},"routing":{"config":{"routerClass":"sap.m.routing.Router"},"routes":[{"name":"UserAttributesList","target":"UserAttributesListTarget","pattern":":?query:"},{"name":"UserAttributesDetail","target":"UserAttributesDetailTarget","pattern":"UserAttributes({key}):?query:"}],"targets":{"UserAttributesListTarget":{"type":"Component","id":"UserAttributesListTarget","name":"sap.fe.templates.ListReport","options":{"settings":{"contextPath":"/UserAttributes","initialLoad":true,"navigation":{"UserAttributes":{"detail":{"route":"UserAttributesDetail"}}}}}},"UserAttributesDetailTarget":{"type":"Component","id":"UserAttributesDetailTarget","name":"sap.fe.templates.ObjectPage","options":{"settings":{"contextPath":"/UserAttributes","navigation":{}}}}}}}}'
});
//# sourceMappingURL=Component-preload.js.map
